version: '3.8'

services:
  catalog-registry:
    container_name: "catalog-registry"
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: catalog-registry:latest
    ports:
      - "${PORT}:${PORT}"
    links:
      - mongodb
    env_file:
      - .env
    networks:
      - catalog-registry
      - ptx

  mongodb:
    container_name: "catalog-registry-mongodb"
    build:
      context: .
      dockerfile: docker/mongodb/Dockerfile
#    Uncomment to connect mongodb container to mongo compass or another service
#    ports:
#      - "27017:27017"
    volumes:
      - registry_data:/data/db
    networks:
      - catalog-registry

networks:
  catalog-registry:
    name: catalog-registry
    driver: bridge
  ptx:
    name: ptx
    external: true

volumes:
  registry_data:
